# Generated by Django 3.1.1 on 2020-09-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triviaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_question', to='triviaapp.trivia'),
        ),
    ]
