# Generated by Django 3.1.1 on 2020-09-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triviaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='player',
        ),
    ]
