# Generated by Django 3.0.8 on 2020-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triviaapp', '0002_auto_20200915_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='options',
            field=models.ManyToManyField(related_name='trivia_options', to='triviaapp.Option'),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='answer',
            field=models.ManyToManyField(related_name='trivia_answer', to='triviaapp.Option'),
        ),
    ]
