# Generated by Django 3.1.1 on 2020-09-15 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triviaapp', '0005_trivia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='player',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='triviaapp.player'),
            preserve_default=False,
        ),
    ]
